[build]
  publish = "build"
  command = "yarn build"
[build.environment]
  NODE_VERSION = "16.13.1"
  NPM_VERSION = "8.1.2"
  NPM_FLAGS = "--legacy-peer-deps"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
